# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'IOSKlosterneuburg' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unity-iPhone

#target 'Unity-iPhone Tests' do
#   inherit! :search_paths
    # Pods for testing
# end

  # Pods for ble-beacon-scan
  pod 'KontaktSDK', '~> 1.3'
  pod 'SwiftKeychainWrapper', '~> 3.0'

end
